#!/bin/bash
set -e

usage() {
    echo "Usage: $0 [dev|prod]"
    echo ""
    echo "  dev   - Backend JAR + Frontend npm run dev (no Docker)"
    echo "  prod  - Backend + Frontend in Docker (8080 + 3000)"
    echo ""
    exit 1
}

# Development mode (no Docker)
dev_mode() {
    echo "======================================"
    echo "🚀 Starting Development Environment"
    echo "======================================"

    if [ -f ".env" ]; then
        set -a; source .env; set +a
        echo "✅ Loaded .env"
    else
        echo "⚠️  .env not found, using defaults"
    fi

    echo ""
    echo "Backend:  http://localhost:8080"
    echo "Frontend: http://localhost:3000 (hot-reload)"
    echo "Database: ${DB_URL}"
    echo ""

    # Generate frontend/.env
    echo "VITE_API_URL=http://localhost:8080" > frontend/.env
    echo "VITE_WS_URL=http://localhost:8080/ws" >> frontend/.env
    echo "✅ Generated frontend/.env"

    if [ ! -f "mvnw" ]; then echo "❌ Maven wrapper not found"; exit 1; fi

    if [ ! -f "target/davomat-backend.jar" ]; then
        echo "⚠️  JAR not found. Building..."
        ./mvnw clean package -DskipTests
    fi

    mkdir -p logs

    echo "📦 Starting Backend (port 8080)..."
    java -jar target/davomat-backend.jar > logs/backend-dev.log 2>&1 &
    BACKEND_PID=$!
    echo "✅ Backend started (PID: $BACKEND_PID)"

    trap "echo ''; echo '🛑 Stopping backend...'; kill $BACKEND_PID 2>/dev/null; exit" INT TERM EXIT

    echo "⏳ Waiting for backend..."
    sleep 5

    echo ""
    echo "🎨 Starting Frontend (port 3000)..."
    cd frontend
    npm run dev
}

# Production mode (both in Docker)
prod_mode() {
    echo "======================================"
    echo "🚀 Davomat Production Deployment"
    echo "======================================"

    command -v docker >/dev/null 2>&1 || { echo "❌ Docker not found"; exit 1; }

    if [ ! -f ".env" ]; then
        echo "❌ .env not found. Run: cp .env.example .env"
        exit 1
    fi

    set -a; source .env; set +a

    echo "✅ Prerequisites OK"
    echo "🗄️  Database: ${DB_URL}"
    echo "🌐 Host IP:   ${HOST_IP}"
    echo ""

    # Generate frontend/.env for Docker build
    cat > frontend/.env << EOF
# Frontend Environment Variables (Auto-generated by deploy.sh)
VITE_API_URL=http://${HOST_IP}:${APP_PORT:-8080}
VITE_WS_URL=http://${HOST_IP}:${APP_PORT:-8080}/ws
EOF
    echo "✅ Generated frontend/.env"
    echo "   VITE_API_URL=http://${HOST_IP}:${APP_PORT:-8080}"
    echo "   VITE_WS_URL=http://${HOST_IP}:${APP_PORT:-8080}/ws"
    echo ""

    if [ ! -f "mvnw" ]; then echo "❌ Maven wrapper not found"; exit 1; fi

    echo "📦 Building backend JAR..."
    ./mvnw clean package -DskipTests
    echo "✅ Backend built"
    echo ""

    mkdir -p frontend/dist

    echo "🎨 Building frontend..."
    cd frontend
    npm install --silent
    npm run build
    if [ ! -d "dist" ]; then
        echo "❌ Frontend build failed"
        exit 1
    fi
    cd ..
    echo "✅ Frontend built: frontend/dist/"
    echo ""

    echo "🐳 Building Docker images..."
    docker compose down 2>/dev/null || true
    docker compose build
    echo ""

    echo "🚀 Starting services..."
    docker compose up -d

    echo ""
    echo "======================================"
    echo "✅ Deployment Complete!"
    echo "======================================"
    echo ""
    echo "🌐 Frontend: http://${HOST_IP}:3000"
    echo "🔌 Backend:  http://${HOST_IP}:8080"
    echo "📚 API Docs: http://${HOST_IP}:8080/swagger-ui.html"
    echo ""
    echo "📊 Logs:  docker compose logs -f"
    echo "🛑 Stop:  docker compose down"
    echo "======================================"
}

MODE="${1:-prod}"

case "$MODE" in
    dev)
        dev_mode
        ;;
    prod)
        prod_mode
        ;;
    *)
        usage
        ;;
esac